### ISSUE TITLE
First pass build fails

### ISSUE THREAD

**Issue by oniice** [thelevicole/minify-laravel-jigsaw-output-plugin#1]
First off thanks for buildings this! Was just about to make it myself!!

I have found an issue when you build in any environment - and it has not been built before, then the plugin will fail and error with the `Input location build_xyz does not exist.`.

I've tried to search through the mix/jigsaw plugins to see if there is any other event that will emit after the files have been generated, but cannot see anything :(

This makes me also think that if this is a race condition - could there be some instances where some files are not minified because they haven't finished being created/updated?

**Comment by thelevicole** [comment]
I have published fixed to npm in version 1.0.2. The issue was caused by validating the input before the build process had completed and resolved by validating input after on the `jigsawDone` hook.

Use `npm update @thelevicole/webkit-minify-jigsaw-output` for the latest version.
